##############
# DEFINE PATHS
##############
OUTDIR: OUTPUT # output directory
AGGRMATRIX: TESTDATA/small_aggr/filtered_feature_bc_matrix.h5 # aggregated H5 file
AGGRFILE: TESTDATA/small_aggr/aggregation.csv # aggregation file used with cellranger aggre
SAMPLE_EXTRACTION_FROMCOL: library_id # library_id or molecule_h5
INDIVDIR: TESTDATA/unaggr # individual samples directory

##########
# METADATA
##########
SPECIES: HUMAN

#######################################
# WORKFLOW STEPS - set to True or False
#######################################
CELL_PHASE_ASSIGNMENT: True # cell cycle phase classification from Scran
# normalizations
SCRAN_DECONVOLUTION: False
SCRAN_DECONVOLUTION_INDIVIDUAL: False
SEURAT_SCTRANSFORM: True
# analysis
SEURAT_PIPE: True # Seurat analysis after normalization

#######################################
# VARIABLE BELOW SHOULD NOT BE MODIFIED
#######################################
OPTIONAL_STEPS: ['CELL_PHASE_ASSIGNMENT'] # all optional steps available
NORMALIZATIONS: ['SCRAN_DECONVOLUTION','SCRAN_DECONVOLUTION_INDIVIDUAL','SEURAT_SCTRANSFORM'] # all normalization methods available
DEFAULT_NORMALIZATION: SCRAN_DECONVOLUTION # default normalization

# COMPLETION FILES
STEP_CELL_PHASE_ASSIGNMENT: step3_cell_phase_assignment
STEP_SCRAN_DECONVOLUTION: step6_scran_deconvolution
STEP_SCRAN_DECONVOLUTION_INDIVIDUAL: step6_scran_deconvolution_merged
STEP_SEURAT_SCTRANSFORM: step6_seurat_sctransform
STEP_SEURAT_PIPE_SCRAN_DECONVOLUTION: step7_seurat_pipe_scran_deconvolution
STEP_SEURAT_PIPE_SCRAN_DECONVOLUTION_INDIVIDUAL: step7_seurat_pipe_scran_deconvolution_merged
STEP_SEURAT_PIPE_SEURAT_SCTRANSFORM: step7_seurat_pipe_seurat_sctransform
#STEP_SEURAT_PIPE: step_seurat3_pipe

################
# RESOURCE FILES
################
HUMAN_RIBOGENESFILE: mart_export_RiboGenes_GO0005840_human.txt # ribosomal genes file
MOUSE_RIBOGENESFILE: mart_export_RiboGenes_GO0005840_mouse.txt # ribosomal genes file